export const siteConfig = {
  name: 'ConvertHub',
  shortName: 'ConvertX',
  description: 'Fast, free, and secure online file, unit, data, currency, audio, and video conversion tools with zero friction and privacy-first auto-purge.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://converthub.com',
  ogImage: 'https://converthub.com/og',
  links: {
    twitter: 'https://twitter.com/ConvertHub',
    github: 'https://github.com/converthub',
  },
  author: 'Lapvy Enterprises',
  keywords: [
    'online converter',
    'free file converter',
    'PDF to Word',
    'JPG to PDF',
    'HEIC to JPG',
    'video converter',
    'audio converter',
    'unit converter',
    'currency converter',
    'live forex rates',
    'land area converter',
    'weight converter',
    'data format converter',
  ],
  navItems: [
    { label: 'Documents', href: '/convert/document' },
    { label: 'Images', href: '/convert/image' },
    { label: 'Video & Audio', href: '/convert/media' },
    { label: 'Units', href: '/convert/unit' },
    { label: 'Currency', href: '/convert/currency' },
    { label: 'Developer & Data', href: '/convert/developer' },
  ],
};

