export const siteConfig = {
  name: 'ApexTools',
  shortName: 'ApexTools.app',
  description: 'Fast, free, and secure online file, unit, data, currency, audio, video, and hardware utility tools with zero friction and privacy-first auto-purge.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://apextools.app',
  ogImage: 'https://apextools.app/og',
  links: {
    twitter: 'https://twitter.com/ApexToolsApp',
    github: 'https://github.com/apextools',
  },
  author: 'Lapvy Enterprises',
  keywords: [
    'online converter',
    'free file converter',
    'PDF to Word',
    'JPG to PDF',
    'HEIC to JPG',
    'video converter',
    'audio converter',
    'unit converter',
    'currency converter',
    'live forex rates',
    'land area converter',
    'weight converter',
    'data format converter',
    'webcam test online',
    'microphone test online',
    'mic visualizer',
    'speaker stereo sound test',
    'dead pixel tester',
    'screen refresh rate tester hz',
    'keyboard ghosting test',
    'mouse double click tester',
    'gamepad controller stick drift test',
    'video call readiness check',
    'audio trimmer online',
    'ringtone cutter mp3',
    'audio joiner merger',
    'voice recorder online mic',
    'audio speed pitch changer',
    'volume booster 300%',
    'wav to mp3 320kbps',
    'mp3 to wav lossless',
  ],
  navItems: [
    { label: 'Documents', href: '/convert/document' },
    { label: 'Images', href: '/convert/image' },
    { label: 'Audio Studio', href: '/convert/audio' },
    { label: 'Video & Media', href: '/convert/media' },
    { label: 'Units', href: '/convert/unit' },
    { label: 'Currency', href: '/convert/currency' },
    { label: 'Developer & Data', href: '/convert/developer' },
    { label: 'Hardware Tests', href: '/convert/hardware' },
  ],
};

